import { registerBlockType } from "@wordpress/blocks";
import { __ } from "@wordpress/i18n";
import { useBlockProps } from "@wordpress/block-editor";

// This will be the component for one-to-one classes.
const OneToOneClassModal = () => {
  return (
    <div>
      <h2>One-to-one Class</h2>
      <p>Details about the class will go here.</p>
    </div>
  );
};

// We might have other components for other event types in the future.
// const CourseModal = () => { ... };
// const AvailabilityModal = () => { ... };

registerBlockType("custom-theme/selected-event-modal", {
  title: __("Selected Event Modal", "custom-theme"),
  category: "widgets",
  icon: "welcome-widgets-menus",
  attributes: {},
  edit: () => {
    const blockProps = useBlockProps();

    return (
      <div {...blockProps}>
        <p style={{ fontSize: 12, color: "#555" }}>
          {__(
            "This block opens a modal when an event is selected in the calendar. The content of the modal is generated by React components.",
            "custom-theme"
          )}
        </p>
      </div>
    );
  },
  save: () => null,
});